souffle: souffle::RWOperation Class Reference
souffle::RWOperation Class Reference
An IO directive is a registry describing a single I/O operation; the registry contains key/value pairs describing the nature of the I/O operation.
#include <RWOperation.h>
Public Member Functions
const std::string & get (const std::string &key) const
get value for a given key
const std::string & getOr (const std::string &key, const std::string &defaultValue) const
get value for a given key; if not found, return default value.
bool has (const std::string &key) const
check whether key exists
bool isEmpty () const
check whether registry is empty
RWOperation ()=default
RWOperation (const std::map< std::string, std::string > &directiveMap)
void set (const std::string &key, const std::string &value)
set value for a given key
virtual ~RWOperation ()=default
Protected Attributes
std::map< std::string, std::string > registry
key/value registry for a I/O directive
Detailed Description
An IO directive is a registry describing a single I/O operation; the registry contains key/value pairs describing the nature of the I/O operation.
Definition at line 33 of file RWOperation.h.
Constructor & Destructor Documentation
RWOperation() [1/2]
souffle::RWOperation::RWOperation () default
RWOperation() [2/2]
souffle::RWOperation::RWOperation (const std::map< std::string, std::string > & directiveMap) inline
Definition at line 36 of file RWOperation.h.
References registry, and ~RWOperation().
{
         for (const auto& pair : directiveMap) {
             registry[pair.first] = pair.second;
         }
     }
~RWOperation()
virtual souffle::RWOperation::~RWOperation () virtual default
Referenced by RWOperation().
Member Function Documentation
get()
const std::string& souffle::RWOperation::get (const std::string & key) const inline
get value for a given key
Definition at line 53 of file RWOperation.h.
References registry.
Referenced by souffle::ReadFileCSV::getFileName(), souffle::IOSystem::getReader(), souffle::IOSystem::getWriter(), souffle::ReadFileCSV::ReadFileCSV(), souffle::ReadStream::ReadStream(), souffle::WriteCoutCSV::WriteCoutCSV(), souffle::WriteFileCSV::WriteFileCSV(), souffle::WriteFileCSV::writeNextTuple(), and souffle::WriteStream::WriteStream().
{
         if (registry.count(key) == 0) {
             throw std::invalid_argument("Requested IO directive <" + key + "> was not specified");
         }
         return registry.at(key);
     }
getOr()
const std::string& souffle::RWOperation::getOr (const std::string & key, const std::string & defaultValue) const inline
get value for a given key; if not found, return default value.
Definition at line 63 of file RWOperation.h.
References has(), and registry.
Referenced by souffle::ReadFileCSV::getFileName(), and souffle::ReadStreamCSV::getInputColumnMap().
{
         if (this->has(key)) {
             return registry.at(key);
         }
         return defaultValue;
     }
has()
bool souffle::RWOperation::has (const std::string & key) const inline
check whether key exists
Definition at line 80 of file RWOperation.h.
References registry.
Referenced by getOr(), souffle::WriteFileCSVFactory::getWriter(), souffle::ReadFileCSV::ReadFileCSV(), souffle::WriteCoutCSV::WriteCoutCSV(), souffle::WriteFileCSV::WriteFileCSV(), and souffle::WriteFileCSV::writeNextTuple().
{
         return registry.count(key) > 0;
     }
isEmpty()
bool souffle::RWOperation::isEmpty () const inline
check whether registry is empty
Definition at line 46 of file RWOperation.h.
References registry.
{
         return registry.empty();
     }
set()
void souffle::RWOperation::set (const std::string & key, const std::string & value) inline
set value for a given key
Definition at line 73 of file RWOperation.h.
References registry.
{
         registry[key] = value;
     }
Field Documentation
registry
std::map<std::string, std::string> souffle::RWOperation::registry protected
key/value registry for a I/O directive
Definition at line 86 of file RWOperation.h.
Referenced by get(), getOr(), has(), isEmpty(), RWOperation(), and set().
The documentation for this class was generated from the following file:
RWOperation.h